[default]
src = "./src"
out = "./out"
libs = "./lib"
test = "./test"

[rpc_endpoints]
sepolia = "${https://sepolia.infura.io/v3/139c21648a054fe9afc4bf9b880cb9a7}"
[verifier]
etherscan_api_key ="QVCDC3V98FBX3ISY1WAZ7DXF42857UM3WT"
